baseurl = "http://rafael-azevedo.github.io/"
contentdir = "content"
publishdir = "public"
languageCode = "en-us"
title = "Rafael Azevedo"
author = "Rafael Azevedo"
[indexes]
   category = "categories"
   tag = "tags"
[Params]
AuthorName = "Rafael"
github = "rafael-azevedo"
twitter = "timeandaraf"
email = "mail@rafaelazevedo.me"
cover = "/images/background-cover.jpg"
logo = "/images/RafaelAzevedo.jpg"
disqusShortname = "rafael-azevedo"
yourName = "Rafael Azevedo"
description = "Problem Solver, Gopher, Monitoring Enthusiast"
footerLine2 = "<a href='https://twitter.com/search?q=%23golang&src=tyah'>#GOLANG</a>"
footerLine3 = "Powered by <a href='http://gohugo.io'>HUGO</a>"
aboutme = "/pages/aboutme"
blog = ""